language: node_js
node_js: stable
script:
  - npm run lint
  - npm run build
deploy:
  local-dir: ./.next
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
